# Site wide configuration

title:            Eric Libby's Research Page
locale:           en_US
url: http://ericlibby.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Eric Libby
  avatar: eric_profile.jpg
  avatar2: eric_profile3.jpg
  avatar3: eric_profile5.jpg
  avatar4: eric_profile2.jpg
  avatar5: eric_profile4.jpg
  avatar6: eric_profile6.jpg

  bio: "Research fellow at the Sante Fe Institute studying the evolution of biological complexity"
  email: elibby@santafe.edu
  disqus-shortname:
  scholar: r7I-dmgAAAAJ&hl=en
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-74140324-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
